config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|hi/ do
    root to: "enquiries#index"
    resources :enquiries , only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
	validates :firstname, length: { minimum: 2 }
	validates :lastname, length: { minimum: 2 }
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	validates :message, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  around_action :switch_locale
  before_action :set_locale
  before_action :set_no_cache

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  private

  def set_locale
    @locale ||= params[:locale] || session[:locale] || I18n.default_locale
    I18n.locale = session[:locale] = @locale
  end

  def set_no_cache
    response.headers['Cache-Control'] = 'no-cache, no-store, max-age=0, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
  end

end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController

  def index
    @enquiry = Enquiry.new(params[:enquiry])
  end

  def create
    @enquiry = Enquiry.new(enquiry_params)
    if @enquiry.save
      EnquiryMailer.with(enquiry: @enquiry).enquiry_info.deliver_later
      flash[:notice] = (t 'form.success')
      redirect_to root_path
    else
      respond_to do |format|
        format.html { render 'index' }
      end
    end
  end

  private
  def enquiry_params
    params.require(:enquiry).permit(:firstname, :lastname, :email, :phone_number, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/index.html.erb
<div class="container-contact100">
	<div class="wrap-contact100">
		<%= form_with scope: :enquiry, url: enquiries_path, local: true, class: 'contact100-form validate-form' do |form| %>
			<% flash.each do |type, msg| %>
				<div class="alert alert-info">
					<%= msg %>
				</div>
			<% end %>
			<% if @enquiry.errors.any? %>
				<div id='error_explanation'>
					<h5><%= (t 'form.error') %></h5>
					<% @enquiry.errors.full_messages.each do |msg| %>
						<p><%= msg %></p>
					<% end %>
				</div>
			<% end %>
			<span class="contact100-form-title">
				<%= (t 'form.send_msg.title') %>
			</span>
			<label class="label-input100" for="first-name"><%= (t 'form.name.title') %></label>
			<div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="Type first name">
				<%= form.text_field :firstname, class: 'input100', placeholder: (t 'form.name.first') %>
				<span class="focus-input100"></span>
			</div>

			<div class="wrap-input100 rs2-wrap-input100 validate-input" data-validate="Type last name">
				<%= form.text_field :lastname, class: 'input100', placeholder: (t 'form.name.last') %>
				<span class="focus-input100"></span>
			</div>

			<label class="label-input100" for="email"><%= (t 'form.email.title') %></label>
			<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
				<%= form.text_field :email, class: 'input100', placeholder: (t 'form.email.example') %>
				<span class="focus-input100"></span>
			</div>

			<label class="label-input100" for="phone"><%= (t 'form.phone.title') %></label>
			<div class="wrap-input100">
				<%= form.text_field :phone_number, class: 'input100', placeholder: (t 'form.phone.example') %>
				<span class="focus-input100"></span>
			</div>

			<label class="label-input100" for="message"><%= (t 'form.message.title') %></label>
			<div class="wrap-input100 validate-input" data-validate = "Message is required">
				<%= form.text_area :message, size: '50x10', class: 'input100', placeholder: (t 'form.message.example') %>
				<span class="focus-input100"></span>
			</div>

			<div class="container-contact100-form-btn">
				<%= form.submit (t 'form.send_msg.btn'), class: 'contact100-form-btn' %>
			</div>
		<% end %>

		<div class="contact100-more flex-col-c-m" style="background-image: url('images/bg-01.jpg');">
			<div class="flex-w size1 p-b-47">
				<div class="txt1 p-r-25">
					<span class="lnr lnr-map-marker"></span>
				</div>

				<div class="flex-col size2">
					<span class="txt1 p-b-20">
						<%= (t 'address.title') %>
					</span>

					<span class="txt2">
						<%= (t 'address.full_address') %>
					</span>
				</div>
			</div>

			<div class="dis-flex size1 p-b-47">
				<div class="txt1 p-r-25">
					<span class="lnr lnr-phone-handset"></span>
				</div>

				<div class="flex-col size2">
					<span class="txt1 p-b-20">
						<%= (t 'contact.title') %>
					</span>

					<span class="txt3">
						<%= (t 'contact.number') %>
					</span>
				</div>
			</div>

			<div class="dis-flex size1 p-b-47">
				<div class="txt1 p-r-25">
					<span class="lnr lnr-envelope"></span>
				</div>

				<div class="flex-col size2">
					<span class="txt1 p-b-20">
						<%= (t 'support.title') %>
					</span>

					<span class="txt3">
						<%= (t 'support.email') %>
					</span>
				</div>
			</div>
		</div>
	</div>
</div>
<div class='language-selector'>
	<%= (t 'language.title') %>
	<ul>
		<li><%= link_to (t 'language.en'), url_for( :locale => 'en' ) %></li>
		<li><%= link_to (t 'language.hi'), url_for( :locale => 'hi' ) %></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Form</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>